[package]
name = "hello-stm32f3"
version = "0.1.0"
authors = ["Oskar Thoren <ot@oskarthoren.com>"]
edition = "2018"

[dependencies]
cortex-m-semihosting = "*"
cortex-m = "*"
cortex-m-rt = "*"
panic-semihosting = "*"

[dependencies.stm32f3]
version = "0.6.0"
features = ["stm32f303", "rt"]